backend:
  name: git-gateway
  branch: main # or your default branch

media_folder: 'content/images'
public_folder: '/images'

collections:
  - name: 'events'
    label: 'Events'
    folder: 'content/events'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'string' }
      - {
          label: 'Background Color',
          name: 'background-color',
          widget: 'string',
        }
      - { label: 'Font', name: 'font', widget: 'string' }
      - { label: 'Font Size', name: 'font-size', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Color', name: 'color', widget: 'string' }
      - {
          label: 'Background Color',
          name: 'background-color',
          widget: 'string',
        }
      - { label: 'Font', name: 'font', widget: 'string' }
      - { label: 'Font Size', name: 'font-size', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
